spring:
  application:
    name: trailnote-api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/trailnote?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

mybatis-plus:
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  environment: local
  version: 0.0.1-SNAPSHOT
